// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyChwbgLFJFYBdpf-qeWPLEV_PQZXHaXlpw","authDomain":"rpgcreation-70a80.firebaseapp.com","databaseURL":"https://rpgcreation-70a80-default-rtdb.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"20","syncVariableStart":"11","syncVariableEnd":"20"}}
];
